## This file generated by InlineX::C2XS (version 0.22) using Inline::C (version 0.55)
package Math::GMPz::Random;
use strict;
use warnings;

require Exporter;
*import = \&Exporter::import;
require DynaLoader;

$Math::GMPz::Random::VERSION = '0.39';

DynaLoader::bootstrap Math::GMPz::Random $Math::GMPz::Random::VERSION;

@Math::GMPz::Random::EXPORT = ();
@Math::GMPz::Random::EXPORT_OK = ();

sub dl_load_flags {0} # Prevent DynaLoader from complaining and croaking

1;
